### PR TITLE
feat: addAssertFields

### PR DESCRIPTION
**Pull request by jacoobes**

### CODE REVIEW

**Review by SrIzan10 — CHANGES_REQUESTED** [review]
why //@ts-nocheck?

**Comment by jacoobes** [comment]
typescript configurations may vary across users,

**Comment by SrIzan10** [comment]
ah kay

**Comment by SrIzan10** [comment]
put value, not mcUsernameInput lol

**Comment by EvolutionX-10** [comment]
pretty sure people wont even get what the plugin does when they will see the name, they'll only get it after looking at code/jsdoc, but nice plugin gg

**Pull request merged**
