### PR TITLE
feat: Adds nsfwOnly plugin

### PR DESCRIPTION
**Pull request by Benzo-Fury**

### CODE REVIEW

**Comment by EvolutionX-10** [comment]
dude 1 plugin per pr please
this way if bugs are introduced they can be backtracked easily
cut the channelOnly file and paste in new branch and pr it off

**Comment by jacoobes** [comment]
Yes, could u one pr per plugin so that theres a separation of concern and its easier to track down bugs.

**Comment by Benzo-Fury** [comment]
Didn't even mean to upload the channelOnly. My bad smh

**Comment by jacoobes** [comment]
all good, remove it from here, and make a new pr for the channelOnly

**Review by jacoobes — COMMENTED** [review]
Looks good.
A few refactoring tips if you do wish to improve code quality
- Line 47: result could be put directly into Line 49, inlining a variable
- Line 44: insert semicolon
- Make nsfwOnly parameters an object to simulate named parameters. This way, when at callsite, it is more declarative

```ts
import { nsfwOnly } from "../plugins/nsfwOnly"; //(change if need be)
import { sernModule, CommandType } from "@sern/handler";
export default commandModule({
    plugins: [ nsfwOnly({ onFail:  'response', ephemeral:  true/false}) ],
    execute: (ctx) => {
       //your code here
    }
})
```

**Comment by jacoobes** [comment]
And make sure to run prettier on it as well. After that, should be good to merge.

**Comment by Benzo-Fury** [comment]
> And make sure to run prettier on it as well. After that, should be good to merge.

Pretty sure I did run prettier on it.

> all good, remove it from here, and make a new pr for the channelOnly

No alg. Wont upload that one. I didn't mean to upload it before either.

> Looks good. A few refactoring tips if you do wish to improve code quality

Will do these aswell.

**Review by jacoobes — APPROVED** [review]

**Pull request merged**
