### PR TITLE
feat: better gen-list + pr template

### PR DESCRIPTION
**Pull request by jacoobes**
supercharged the gen-list script to include hash, description, example, and more metadata

### CODE REVIEW

**Comment by SrIzan10** [comment]
@jacoobes add me as a reviewer please

**Comment by jacoobes** [comment]
@SrIzan10 will add @compatible tag so we know the minimum version a user can use this plugin

**Comment by SrIzan10** [comment]
alright, any thoughts on starting to make the directory structure I talked about? do you have any other idea?

**Comment by jacoobes** [comment]
Remind me what that is again

Vào Th 5, 24 thg 8, 2023 lúc 11:13 SA Izan Gil Cruz <
***@***.***> đã viết:

**Comment by SrIzan10** [comment]
"we have a plugins directory and inside it we have versions (3.0.0, 2.5.0, etc) and inside it we have a javascript and a typescript directory. there should be all plugins for that version there"

**Comment by jacoobes** [comment]
Good idea; another way is to have another json map with git commit sha and
we can maybe restore it from there

Vào Th 5, 24 thg 8, 2023 lúc 11:18 SA Izan Gil Cruz <
***@***.***> đã viết:

**Review by EvolutionX-10 — APPROVED** [review]

**Pull request merged**
