### PR TITLE
feat: add filter plugin

### PR DESCRIPTION
**Pull request by trueharuu**

### CODE REVIEW

**Comment by trueharuu** [comment]
someone un-prettier this from ci

**Review by SrIzan10 — CHANGES_REQUESTED** [review]
add a jsdoc comment on top of the file (like other plugins)

**Comment by jacoobes** [comment]
@trueharuu force push ur branch with ur formatting to override

**Comment by trueharuu** [comment]
> add a jsdoc comment on top of the file (like other plugins)

there's a ts restriction stopping me from doing that

**Comment by trueharuu** [comment]
to be added via commit without pr

**Pull request closed without merging**
