### PR TITLE
chore: update publish.ts to use backwards compatible service

### PR DESCRIPTION
**Pull request by jacoobes**

### CODE REVIEW

**Comment by Peter-MJ-Parker** [comment]
What if some users decide to download sern handler > v3 and need to use useContainer? If they download this plugin after the successful merge, they won't know how to make it backwards compatible with v1 or v2. So maybe invoke a check to see what version they're running before defining the client.

**Comment by SrIzan10** [comment]
we're thinking about a good way of keeping old versions of plugins that are compatible with older versions of sern handler, so you'll probably need to wait until we get that sorted out.
in the meantime use github's file commit history and try until one version works

**Comment by jacoobes** [comment]
Marv brings up a good point that I forgot to cover, good amount of ppl are
still on v2, will have to think of something to include version 2. Might
port Service backwards but idk yet

Vào Th 2, 31 thg 7, 2023 lúc 11:16 SA SrIzan10 ***@***.***>
đã viết:

**Comment by EvolutionX-10** [comment]
So you're gonna work on it or should I merge this one?

**Comment by SrIzan10** [comment]
merge for now (or add a comment telling how to edit the plugin to make it work)

**Comment by Peter-MJ-Parker** [comment]
I would like to try something in the plugin and possibly be able to invoke the client either way. I have an idea on how to invoke other's clients.

**Comment by jacoobes** [comment]
On hold now, don't merge, want a nice solution for backwards compatibility 
useContainer will be removed in v4 so it'll be a while

**Comment by Peter-MJ-Parker** [comment]
So `const client = Service('@sern/client') ?? useContainer('@sern/client')` seems to be a good fix for me. The user would still need to input their path to the specific function being used.

**Comment by jacoobes** [comment]
> So `const client = Service('@sern/client') ?? useContainer('@sern/client')` seems to be a good fix for me. The user would still need to input their path to the specific function being used.

not bad. however, we need to dynamically Service from sern handler and useContainer from index.js in the plugin. If you try to run an import that doesnt exist, the application crashes

**Comment by SrIzan10** [comment]
so a try catch?
edit: my just woken up brain didn't notice that a try catch doesn't catch import errors

**Comment by jacoobes** [comment]
> so a try catch? edit: my just woken up brain didn't notice that a try catch doesn't catch import errors

it should be able to, try catch is probably the way to go

**Comment by SrIzan10** [comment]
```ts
let client
try {
    client = (await import('@sern/handler')).Service('@sern/client')
} catch {
    const {useContainer} = await import('../index.js')
    [client] = useContainer("@sern/client");
}
```
probably like that? (code made in github comments)
EDIT: fix random code errors

**Comment by Peter-MJ-Parker** [comment]
That's actually what I thought of originally.

**Comment by jacoobes** [comment]
> ```ts
> let client
> try {
>     const client = (import('@sern/handler')).Service('@sern/client')
> } catch {
>     const {useContainer} = import('../index.js')
>     const [client] = useContainer("@sern/client");
> }
> ```
> 
> probably like that? (code made in github comments)

yes, make sure to await import and reassign to let client

**Comment by SrIzan10** [comment]
yes, my bad...

**Comment by Peter-MJ-Parker** [comment]
```ts
let client
try {
   client = (await import('@sern/handler')).Service('@sern/client')
} catch {
    const {useContainer} = await import('../index.js')
    client = useContainer("@sern/client")[0];
}
```

**Comment by Peter-MJ-Parker** [comment]
> ```ts
> let client
> try {
>    client = (await import('@sern/handler')).Service('@sern/client')
> } catch {
>     const {useContainer} = await import('../index.js')
>     client = useContainer("@sern/client")[0];
> }
> ```

I feel like my promise is being resolved correctly tho.

**Comment by jacoobes** [comment]
if u can implement that, test, evo will merge

**Review by SrIzan10 — APPROVED** [review]

**Review by EvolutionX-10 — APPROVED** [review]

**Pull request merged**
